### ISSUE TITLE
Parsing S-expression with inner quotes and brackets

### ISSUE THREAD

**Issue by wybczu** [dryruby/sxp.rb#12]
When I try to parse following expression (it's an output of `puppet parser dump`)

```
(class dummy (parameters (= param '"(this is just a test)"')) ())
```

I'm getting a parser error

```
/home/luk/tmp/sxp-test/vendor/bundle/ruby/2.3.0/gems/sxp-1.0.0/lib/sxp/reader.rb:265:in `read_char': unexpected end of input (SXP::Reader::EOF)
	from /home/luk/tmp/sxp-test/vendor/bundle/ruby/2.3.0/gems/sxp-1.0.0/lib/sxp/reader/basic.rb:42:in `read_string'
	from /home/luk/tmp/sxp-test/vendor/bundle/ruby/2.3.0/gems/sxp-1.0.0/lib/sxp/reader/basic.rb:18:in `read_token'
	from /home/luk/tmp/sxp-test/vendor/bundle/ruby/2.3.0/gems/sxp-1.0.0/lib/sxp/reader.rb:150:in `read'
	from /home/luk/tmp/sxp-test/vendor/bundle/ruby/2.3.0/gems/sxp-1.0.0/lib/sxp/reader.rb:176:in `block in read_list'
	from /home/luk/tmp/sxp-test/vendor/bundle/ruby/2.3.0/gems/sxp-1.0.0/lib/sxp/reader.rb:175:in `catch'
	from /home/luk/tmp/sxp-test/vendor/bundle/ruby/2.3.0/gems/sxp-1.0.0/lib/sxp/reader.rb:175:in `read_list'
	from /home/luk/tmp/sxp-test/vendor/bundle/ruby/2.3.0/gems/sxp-1.0.0/lib/sxp/reader.rb:158:in `read'
	from /home/luk/tmp/sxp-test/vendor/bundle/ruby/2.3.0/gems/sxp-1.0.0/lib/sxp/reader.rb:176:in `block in read_list'
	from /home/luk/tmp/sxp-test/vendor/bundle/ruby/2.3.0/gems/sxp-1.0.0/lib/sxp/reader.rb:175:in `catch'
	from /home/luk/tmp/sxp-test/vendor/bundle/ruby/2.3.0/gems/sxp-1.0.0/lib/sxp/reader.rb:175:in `read_list'
	from /home/luk/tmp/sxp-test/vendor/bundle/ruby/2.3.0/gems/sxp-1.0.0/lib/sxp/reader.rb:158:in `read'
	from /home/luk/tmp/sxp-test/vendor/bundle/ruby/2.3.0/gems/sxp-1.0.0/lib/sxp/reader.rb:176:in `block in read_list'
	from /home/luk/tmp/sxp-test/vendor/bundle/ruby/2.3.0/gems/sxp-1.0.0/lib/sxp/reader.rb:175:in `catch'
	from /home/luk/tmp/sxp-test/vendor/bundle/ruby/2.3.0/gems/sxp-1.0.0/lib/sxp/reader.rb:175:in `read_list'
	from /home/luk/tmp/sxp-test/vendor/bundle/ruby/2.3.0/gems/sxp-1.0.0/lib/sxp/reader.rb:158:in `read'
	from /home/luk/tmp/sxp-test/vendor/bundle/ruby/2.3.0/gems/sxp-1.0.0/lib/sxp/reader.rb:77:in `read'
	from /home/luk/tmp/sxp-test/vendor/bundle/ruby/2.3.0/gems/sxp-1.0.0/lib/sxp.rb:81:in `read'
```

However if I switch `'` with `"`

```
(class dummy (parameters (= param "'(this is just a test)'")) ())
```

it works perfectly.

I'm wondering if anything between `' '` should be treated as a string too. After patching `lib/sxp/reader/basic.rb`

```
diff --git a/lib/sxp/reader/basic.rb b/lib/sxp/reader/basic.rb
index e34af45..5e47b09 100644
--- a/lib/sxp/reader/basic.rb
+++ b/lib/sxp/reader/basic.rb
@@ -15,7 +15,7 @@ module SXP; class Reader
     def read_token
       case peek_char
         when ?(, ?) then [:list, read_char]
-        when ?"     then [:atom, read_string] #"
+        when ?", ?' then [:atom, read_string] #"
         else super
       end
     end
@@ -36,8 +36,8 @@ module SXP; class Reader
     # @return [String]
     def read_string
       buffer = String.new
-      skip_char # '"'
-      until peek_char == ?" #"
+      skipped_char = skip_char # '"'
+      until peek_char == skipped_char #"
         buffer <<
           case char = read_char
             when ?\\ then read_character
@@ -60,6 +60,7 @@ module SXP; class Reader
         when ?u  then read_chars(4).to_i(16).chr
         when ?U  then read_chars(8).to_i(16).chr
         when ?"  then char #"
+        when ?'  then char #"
         when ?\\ then char
         else char
       end
```

problem seems to be solved.

**Comment by gkellogg** [comment]
Looking at some of the referenced specs for S-Expressions:

* The [S-expression][] wiki page only uses double-quotes for string literals.
* The [Common Lisp] grammar uses a single-quote as a `function` special operator. In this case, which is abbreviated as `#'`.
* In [Schema][] the single quote is used for more general structure quoting, and not for strings.

Adding `'` as an equivalent for `"` is probably not appropriate in general. It _could_ take on this meaning specifically in SPARQL S-Expressions, but that would be incompatible with Jena SSE. But, for input purposes, I could see a SPARQL-specific versions of `read_token` and `read_string`.

What is the application? If there's a particular dialect for Puppet output, then perhaps you might want to consider creating an `SXP::Reader::Puppet` subclass of `Extended` designed specifically for reading puppet output.

[S-expression]: http://en.wikipedia.org/wiki/S-expression
[Scheme]:       http://scheme.info/
[Common Lisp]:  http://en.wikipedia.org/wiki/Common_Lisp
[SPARQL]:       http://openjena.org/wiki/SSE

**Comment by wybczu** [comment]
Thank you! You are right, it seems that double-quotes should be used for string literals.

I will create a class for parsing Puppet look-alike S-expression in my project.

**Comment by gkellogg** [comment]
If you'd like to submit a PR for a Puppet class in this gem, and you think there may be broader appeal, we could include it in a release. Of course, broad support may be more extensive than your specific use cases need.
